services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: uns-calendar-api:latest
    container_name: uns-calendar-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "3002:3002"

  frontend:
    build: .
    image: uns-calendar-frontend:latest
    container_name: uns-calendar-frontend
    restart: "no"
    depends_on:
      - api
    volumes:
      - ./dist:/dist


networks:
  default:
    name: uns-calendar-net
